- name: Install jenkins
  hosts: all
  become: true

  pre_tasks:
    - include_vars: "../env_vars/vars.yml"

  vars:
    jenkins_http_port: "{{ jenkins.jenkins_http_port }}"
  roles:
    - role: geerlingguy.jenkins
